# Redocly configuration file
extends:
  - recommended

rules:
  # OAuth redirect endpoints only return 302 redirects, not 2XX responses
  operation-2xx-response: off
  
  # Public endpoints and health checks don't need 4XX responses
  # OAuth redirects also don't need 4XX responses (they redirect on error)
  operation-4xx-response: off